# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcestatistics',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
