# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-10 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160817_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcestatistics',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
